<a href="https://colab.research.google.com/github/VaishnavWani/Mahchine_Learning/blob/main/Logistic_binary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
# from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
data = pd.read_excel("/content/loan_logistic_regression_dataset.xlsx")

In [ ]:
data.head()

   Age  Monthly_Income  Credit_Score Gender Education_Level  Loan_Approved
0   26           37958           406   Male             PhD              0
1   47           34272           797   Male        Bachelor              1
2   25           28351           649   Male          Master              0
3   41           74724           786   Male          Master              1
4   45           51021           534   Male        Bachelor              0

In [ ]:
dummies_gender = pd.get_dummies(data.Gender, drop_first = True,  prefix="G_").astype(int)
dummies_EL = pd.get_dummies(data.Education_Level, drop_first = True,  prefix="EL_").astype(int)

In [ ]:
data = data.drop(["Gender","Education_Level"], axis=1)

In [ ]:
data

    Age  Monthly_Income  Credit_Score  Loan_Approved
0    26           37958           406              0
1    47           34272           797              1
2    25           28351           649              0
3    41           74724           786              1
4    45           51021           534              0
5    61           48272           829              1
6    50          112099           305              0
7    36           63334           349              0
8    45           61876           738              1
9    30          118622           632              1
10   47           99357           482              1
11   64           54331           721              1
12   48           50034           560              0
13   30           70396           775              1
14   61           82326           533              1
15   60           85697           631              1
16   26           45914           525              0
17   29           60520           769              1
18   22           86726           385              0
19   33           63950           776              1
20   28           98174           547              1
21   41           88463           483              0
22   27           93667           376              0
23   46           68942           385              0
24   22          115399           530              1
25   56           35374           615              0
26   31           84912           700              1
27   36           75741           335              0
28   60          106853           588              1
29   26           34363           461              0
30   31           64790           345              0
31   45           85923           775              1
32   57           86171           698              1
33   25          103857           345              0
34   30           73256           342              0
35   41           23965           590              0
36   23           29560           395              0
37   22           99889           483              0
38   38           60239           530              0
39   53           88245           565              1
40   51           70192           569              1
41   50           59718           641              1
42   29           98582           301              0
43   45          115134           587              1
44   32           45795           508              0
45   63           71988           797              1
46   57          106810           461              1
47   22           65936           555              0
48   29           31001           638              0
49   45           99900           761              1

In [ ]:
data = pd.concat([data,dummies_gender,dummies_EL],axis = 1)

In [ ]:
data

,Age,Monthly_Income,Credit_Score,Loan_Approved,G__Male,EL__High School,EL__Master,EL__PhD
0,26,37958,406,0,1,0,0,1
1,47,34272,797,1,1,0,0,0
2,25,28351,649,0,1,0,1,0
3,41,74724,786,1,1,0,1,0
4,45,51021,534,0,1,0,0,0
5,61,48272,829,1,0,0,1,0
6,50,112099,305,0,1,1,0,0
7,36,63334,349,0,1,0,0,0
8,45,61876,738,1,0,0,0,0
9,30,118622,632,1,0,1,0,0
10,47,99357,482,1,1,0,0,1
11,64,54331,721,1,0,1,0,0
12,48,50034,560,0,1,0,1,0
13,30,70396,775,1,1,1,0,0
14,61,82326,533,1,0,0,0,0
15,60,85697,631,1,1,0,0,0
16,26,45914,525,0,1,1,0,0
17,29,60520,769,1,1,0,0,0
18,22,86726,385,0,0,0,0,0
19,33,63950,776,1,0,0,0,0
20,28,98174,547,1,0,0,1,0
21,41,88463,483,0,1,1,0,0
22,27,93667,376,0,1,1,0,0
23,46,68942,385,0,0,0,0,0
24,22,115399,530,1,1,0,0,0
25,56,35374,615,0,1,0,0,0
26,31,84912,700,1,1,0,0,1
27,36,75741,335,0,1,0,1,0
28,60,106853,588,1,0,1,0,0
29,26,34363,461,0,1,0,0,0
30,31,64790,345,0,1,0,0,0
31,45,85923,775,1,1,0,0,0
32,57,86171,698,1,1,0,0,0
33,25,103857,345,0,0,0,0,0
34,30,73256,342,0,0,0,0,1
35,41,23965,590,0,0,0,0,0
36,23,29560,395,0,0,0,1,0
37,22,99889,483,0,1,0,0,0
38,38,60239,530,0,0,0,1,0
39,53,88245,565,1,0,1,0,0
40,51,70192,569,1,1,0,1,0
41,50,59718,641,1,1,0,0,1
42,29,98582,301,0,1,0,0,0
43,45,115134,587,1,1,0,0,0
44,32,45795,508,0,0,0,1,0
45,63,71988,797,1,1,0,1,0
46,57,106810,461,1,0,0,1,0
47,22,65936,555,0,0,1,0,0
48,29,31001,638,0,0,0,0,1
49,45,99900,761,1,0,0,0,1

In [ ]:
x = data.drop("Loan_Approved",axis = 1)
y = data.Loan_Approved

In [ ]:
x.head()

,Age,Monthly_Income,Credit_Score,G__Male,EL__High School,EL__Master,EL__PhD
0,26,37958,406,1,0,0,1
1,47,34272,797,1,0,0,0
2,25,28351,649,1,0,1,0
3,41,74724,786,1,0,1,0
4,45,51021,534,1,0,0,0

In [ ]:
y.head()

0    0
1    1
2    0
3    1
4    0
Name: Loan_Approved, dtype: int64

In [ ]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y, random_state = 20, test_size=0.2 )

In [ ]:
xtrain = sm.add_constant(xtrain)
xtest = sm.add_constant(xtest)

In [ ]:
xtrain

,const,Age,Monthly_Income,Credit_Score,G__Male,EL__High School,EL__Master,EL__PhD
40,1.0,51,70192,569,1,0,1,0
17,1.0,29,60520,769,1,0,0,0
18,1.0,22,86726,385,0,0,0,0
0,1.0,26,37958,406,1,0,0,1
27,1.0,36,75741,335,1,0,1,0
33,1.0,25,103857,345,0,0,0,0
36,1.0,23,29560,395,0,0,1,0
42,1.0,29,98582,301,1,0,0,0
10,1.0,47,99357,482,1,0,0,1
3,1.0,41,74724,786,1,0,1,0
41,1.0,50,59718,641,1,0,0,1
13,1.0,30,70396,775,1,1,0,0
46,1.0,57,106810,461,0,0,1,0
2,1.0,25,28351,649,1,0,1,0
38,1.0,38,60239,530,0,0,1,0
39,1.0,53,88245,565,0,1,0,0
5,1.0,61,48272,829,0,0,1,0
43,1.0,45,115134,587,1,0,0,0
37,1.0,22,99889,483,1,0,0,0
30,1.0,31,64790,345,1,0,0,0
6,1.0,50,112099,305,1,1,0,0
29,1.0,26,34363,461,1,0,0,0
16,1.0,26,45914,525,1,1,0,0
19,1.0,33,63950,776,0,0,0,0
49,1.0,45,99900,761,0,0,0,1
44,1.0,32,45795,508,0,0,1,0
21,1.0,41,88463,483,1,1,0,0
32,1.0,57,86171,698,1,0,0,0
34,1.0,30,73256,342,0,0,0,1
7,1.0,36,63334,349,1,0,0,0
22,1.0,27,93667,376,1,1,0,0
11,1.0,64,54331,721,0,1,0,0
20,1.0,28,98174,547,0,0,1,0
9,1.0,30,118622,632,0,1,0,0
48,1.0,29,31001,638,0,0,0,1
28,1.0,60,106853,588,0,1,0,0
31,1.0,45,85923,775,1,0,0,0
15,1.0,60,85697,631,1,0,0,0
26,1.0,31,84912,700,1,0,0,1
35,1.0,41,23965,590,0,0,0,0

In [ ]:
# L1 regularization forces convergence
model_fit = logit_model.fit_regularized(method='l1'  , alpha=0.1)
print(model_fit.summary())

Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.11355637258222051
            Iterations: 99
            Function evaluations: 114
            Gradient evaluations: 99
                           Logit Regression Results
==============================================================================
Dep. Variable:          Loan_Approved   No. Observations:                   40
Model:                          Logit   Df Residuals:                       32
Method:                           MLE   Df Model:                            7
Date:                Fri, 26 Jun 2026   Pseudo R-squ.:                  0.9469
Time:                        17:06:22   Log-Likelihood:                -1.4721
converged:                       True   LL-Null:                       -27.726
Covariance Type:            nonrobust   LLR p-value:                 4.637e-09
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const             -28.3591     10.420     -2.722      0.006     -48.782      -7.936
Age                 0.1504      0.110      1.367      0.172      -0.065       0.366
Monthly_Income      0.0001   4.92e-05      2.065      0.039    5.18e-06       0.000
Credit_Score        0.0282      0.012      2.395      0.017       0.005       0.051
G__Male            -0.2941      2.164     -0.136      0.892      -4.536       3.947
EL__High School    -1.7504      3.295     -0.531      0.595      -8.208       4.708
EL__Master          0.0643      2.963      0.022      0.983      -5.744       5.872
EL__PhD             0.0546      3.457      0.016      0.987      -6.721       6.830
===================================================================================

/usr/local/lib/python3.12/dist-packages/statsmodels/discrete/discrete_model.py:2385: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/usr/local/lib/python3.12/dist-packages/statsmodels/discrete/discrete_model.py:2443: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q * linpred)))
/usr/local/lib/python3.12/dist-packages/statsmodels/base/l1_solvers_common.py:71: ConvergenceWarning: QC check did not pass for 1 out of 8 parameters
Try increasing solver accuracy or number of iterations, decreasing alpha, or switch solvers
  warnings.warn(message, ConvergenceWarning)
/usr/local/lib/python3.12/dist-packages/statsmodels/base/l1_solvers_common.py:144: ConvergenceWarning: Could not trim params automatically due to failed QC check. Trimming using trim_mode == 'size' will still work.
  warnings.warn(msg, ConvergenceWarning)

In [ ]:
logit_model = sm.Logit(ytrain,xtrain)
logit_model.fit()

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.000000
         Iterations: 35

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

**Logistic Regression on mtcars dataset**
**Use mpg as response, hp, wt and gear as predictors**

In [ ]:
import pandas as pd
import numpy as np

# from sklearn.model_selection import train_test_split
# import statsmodels.api as sm

from sklearn.model_selection import train_test_split
import statsmodels.api as sm

In [ ]:
dt = pd.read_excel("/content/drive/MyDrive/CDAC_DataBook.xlsx", sheet_name="mtcars")

In [ ]:
dt.head(1)

    mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110   3.9  2.62  16.46   0   1     4     4

In [ ]:
dt = dt.drop(["cyl",'disp','drat','qsec','vs','carb'], axis = 1)

In [ ]:
dt.head()

    mpg   hp     wt  am  gear
0  21.0  110  2.620   1     4
1  21.0  110  2.875   1     4
2  22.8   93  2.320   1     4
3  21.4  110  3.215   0     3
4  18.7  175  3.440   0     3

In [ ]:
am_dummies = pd.get_dummies(dt.am, drop_first = True,  prefix="am_").astype(int)
gear_dummies = pd.get_dummies(dt.gear, drop_first = True,  prefix="gear_").astype(int)

In [ ]:
dt = pd.concat([dt,am_dummies,gear_dummies],axis = 1)

In [ ]:
dt.head()

    mpg   hp     wt  am  gear  am__1  gear__4  gear__5
0  21.0  110  2.620   1     4      1        1        0
1  21.0  110  2.875   1     4      1        1        0
2  22.8   93  2.320   1     4      1        1        0
3  21.4  110  3.215   0     3      0        0        0
4  18.7  175  3.440   0     3      0        0        0

In [ ]:
dt = dt.drop(["am","gear"], axis = 1)

In [ ]:
dt.head()

    mpg   hp     wt  am__1  gear__4  gear__5
0  21.0  110  2.620      1        1        0
1  21.0  110  2.875      1        1        0
2  22.8   93  2.320      1        1        0
3  21.4  110  3.215      0        0        0
4  18.7  175  3.440      0        0        0

In [ ]:
dt['mpg'].median()

19.2

In [ ]:
dt['resp_mpg'] = np.where(dt['mpg']>dt['mpg'].median(),1,0)

In [ ]:
dt.head()

    mpg   hp     wt  am__1  gear__4  gear__5  resp_mpg
0  21.0  110  2.620      1        1        0         1
1  21.0  110  2.875      1        1        0         1
2  22.8   93  2.320      1        1        0         1
3  21.4  110  3.215      0        0        0         1
4  18.7  175  3.440      0        0        0         0

In [ ]:
dt = dt.drop(['mpg'],axis=1)

In [ ]:
dt.head()

    hp     wt  am__1  gear__4  gear__5  resp_mpg
0  110  2.620      1        1        0         1
1  110  2.875      1        1        0         1
2   93  2.320      1        1        0         1
3  110  3.215      0        0        0         1
4  175  3.440      0        0        0         0

In [ ]:
x = dt.drop(['resp_mpg'], axis = 1)
y = dt.resp_mpg

In [ ]:
y.head()

0    1
1    1
2    1
3    1
4    0
Name: resp_mpg, dtype: int64

In [ ]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y, random_state = 20, test_size=0.2 )

In [ ]:
xtrain  = sm.add_constant(xtrain)
xtest = sm.add_constant(xtest)

In [ ]:
xtrain.head()

    const   hp     wt  am__1  gear__4  gear__5
13    1.0  180  3.780      0        0        0
18    1.0   52  1.615      1        1        0
21    1.0  150  3.520      0        0        0
12    1.0  180  3.730      0        0        0
23    1.0  245  3.840      0        0        0

In [ ]:
model = sm.Logit(ytrain , xtrain).fit()

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.000000
         Iterations: 35

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

In [ ]:
print(model.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:               resp_mpg   No. Observations:                   25
Model:                          Logit   Df Residuals:                       19
Method:                           MLE   Df Model:                            5
Date:                Mon, 29 Jun 2026   Pseudo R-squ.:                   1.000
Time:                        16:21:57   Log-Likelihood:            -5.9719e-07
converged:                      False   LL-Null:                       -17.148
Covariance Type:            nonrobust   LLR p-value:                 2.078e-06
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const        431.5439   3.72e+04      0.012      0.991   -7.24e+04    7.32e+04
hp            -0.1025    101.496     -0.001      0.999    -199.030     198.825
wt          -126.0346    1.1e+04     -0.011      0.991   -2.17e+04    2.14e+04
am__1        -66.2305   1.67e+04     -0.004      0.997   -3.28e+04    3.27e+04
gear__4       -4.9199   8385.523     -0.001      1.000   -1.64e+04    1.64e+04
gear__5       42.5967   2.25e+04      0.002      0.998   -4.42e+04    4.42e+04
==============================================================================

Complete Separation: The results show that there iscomplete separation or perfect prediction.
In this case the Maximum Likelihood Estimator does not exist and the parameters
are not identified.